### ISSUE TITLE
切换配置文件时会提示错误

### ISSUE THREAD

**Issue by Aceralon** [Fndroid/clash_for_windows_pkg#1450]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)
Windows 20H2
v0.13.8
**描述**

[//]: # (请具体并清楚地描述遇到的问题)
切换配置时会提示
```
Could not switch to this profile!
Error: network Error
```
但是此时该配置文件已经被使用，Proxies页面可以正常选择，仅Profiles页面未显示选中配置。

**复现**

[//]: # (请描述复现问题的步骤)

1. 任意选择配置

**预期行为**

[//]: # (清晰地描述期望看到的行为)
正常切换且不显示配置错误

**日志**

[//]: # (上传触发问题对应的日志文件)
相关 log
```
time="2020-12-27T15:11:20+08:00" level=info msg="Start initial compatible provider PROXY"
time="2020-12-27T15:11:20+08:00" level=info msg="DNS server listening at: 0.0.0.0:53"
2020/12/27 15:11:20 http: panic serving 127.0.0.1:4889: The specified module could not be found.
goroutine 10 [running]:
net/http.(*conn).serve.func1(0xc00007dae0)
	net/http/server.go:1801 +0x147
panic(0x11d3280, 0x173a5d0)
	runtime/panic.go:975 +0x499
golang.org/x/sys/windows.(*LazyProc).mustFind(...)
	golang.org/x/sys@v0.0.0-20201214210602-f9fddec55a1e/windows/dll_windows.go:325
golang.org/x/sys/windows.(*LazyProc).Addr(...)
	golang.org/x/sys@v0.0.0-20201214210602-f9fddec55a1e/windows/dll_windows.go:333
github.com/Dreamacro/clash/proxy/device/wintun.(*Pool).OpenAdapter(0x0, 0x1284163, 0x5, 0xebe729, 0xc000512540, 0xc00030f300)
	github.com/Dreamacro/clash/proxy/device/wintun/wintun.go:98 +0x22f
github.com/Dreamacro/clash/proxy/device.CreateTUNWithRequestedGUID(0x1284163, 0x5, 0xc0002331f0, 0x2328, 0x1, 0x119a7c0, 0x20, 0x20)
	github.com/Dreamacro/clash/proxy/device/tun_windows.go:117 +0x5a
github.com/Dreamacro/clash/proxy/device.CreateTUN(0x1284163, 0x5, 0x2328, 0xc00030f3dc, 0x4, 0x4, 0xc000166040)
	github.com/Dreamacro/clash/proxy/device/tun_windows.go:106 +0x154
github.com/Dreamacro/clash/proxy/tun.NewTunProxy(0xc0001c5ce0, 0xc00042fad0, 0x2, 0x2, 0x2, 0xc00042fad0, 0x1)
	github.com/Dreamacro/clash/proxy/tun/adapter.go:271 +0xb2
github.com/Dreamacro/clash/proxy.ReCreateTun(0x1, 0xc0001c5ce0, 0xc0003d3eb8, 0x6, 0x0, 0x17b9a68, 0x0, 0x0, 0xc0005124c0, 0x2, ...)
	github.com/Dreamacro/clash/proxy/listener.go:233 +0x5ea
github.com/Dreamacro/clash/hub/executor.updateTun(0xc0000a4b00)
	github.com/Dreamacro/clash/hub/executor/executor.go:132 +0x1f8
github.com/Dreamacro/clash/hub/executor.ApplyConfig(0xc0000a4b00, 0x2000)
	github.com/Dreamacro/clash/hub/executor/executor.go:73 +0x113
github.com/Dreamacro/clash/hub/route.updateConfigs(0x1374de0, 0xc0000f2000, 0xc0002a6100)
	github.com/Dreamacro/clash/hub/route/configs.go:124 +0x16d
net/http.HandlerFunc.ServeHTTP(0x12c05a0, 0x1374de0, 0xc0000f2000, 0xc0002a6100)
	net/http/server.go:2042 +0x4b
github.com/go-chi/chi.(*Mux).routeHTTP(0xc0002004e0, 0x1374de0, 0xc0000f2000, 0xc0002a6100)
	github.com/go-chi/chi@v4.1.2+incompatible/mux.go:431 +0x28b
net/http.HandlerFunc.ServeHTTP(0xc0002200a0, 0x1374de0, 0xc0000f2000, 0xc0002a6100)
	net/http/server.go:2042 +0x4b
github.com/go-chi/chi.(*Mux).ServeHTTP(0xc0002004e0, 0x1374de0, 0xc0000f2000, 0xc0002a6100)
	github.com/go-chi/chi@v4.1.2+incompatible/mux.go:70 +0x50c
github.com/go-chi/chi.(*Mux).Mount.func1(0x1374de0, 0xc0000f2000, 0xc0002a6100)
	github.com/go-chi/chi@v4.1.2+incompatible/mux.go:298 +0x122
net/http.HandlerFunc.ServeHTTP(0xc0002021e0, 0x1374de0, 0xc0000f2000, 0xc0002a6100)
	net/http/server.go:2042 +0x4b
github.com/Dreamacro/clash/hub/route.authentication.func1(0x1374de0, 0xc0000f2000, 0xc0002a6100)
	github.com/Dreamacro/clash/hub/route/server.go:96 +0x3f3
net/http.HandlerFunc.ServeHTTP(0xc000202200, 0x1374de0, 0xc0000f2000, 0xc0002a6100)
	net/http/server.go:2042 +0x4b
github.com/go-chi/chi.(*ChainHandler).ServeHTTP(0xc000222380, 0x1374de0, 0xc0000f2000, 0xc0002a6100)
	github.com/go-chi/chi@v4.1.2+incompatible/chain.go:31 +0x59
github.com/go-chi/chi.(*Mux).routeHTTP(0xc000200420, 0x1374de0, 0xc0000f2000, 0xc0002a6100)
	github.com/go-chi/chi@v4.1.2+incompatible/mux.go:431 +0x28b
net/http.HandlerFunc.ServeHTTP(0xc000220040, 0x1374de0, 0xc0000f2000, 0xc0002a6100)
	net/http/server.go:2042 +0x4b
github.com/go-chi/cors.(*Cors).Handler.func1(0x1374de0, 0xc0000f2000, 0xc0002a6100)
	github.com/go-chi/cors@v1.1.1/cors.go:228 +0x1c6
net/http.HandlerFunc.ServeHTTP(0xc000202080, 0x1374de0, 0xc0000f2000, 0xc0002a6100)
	net/http/server.go:2042 +0x4b
github.com/go-chi/chi.(*Mux).ServeHTTP(0xc000200420, 0x1374de0, 0xc0000f2000, 0xc0002a6300)
	github.com/go-chi/chi@v4.1.2+incompatible/mux.go:86 +0x2d1
net/http.serverHandler.ServeHTTP(0xc000250000, 0x1374de0, 0xc0000f2000, 0xc0002a6300)
	net/http/server.go:2843 +0xaa
net/http.(*conn).serve(0xc00007dae0, 0x1375f20, 0xc000038a40)
	net/http/server.go:1925 +0x8ad
created by net/http.(*Server).Serve
	net/http/server.go:2969 +0x36d
```

**截图**

[//]: # (如果可以，请提供对应问题的截图)
![image.png](https://i.loli.net/2020/12/27/gRBtzfa5G9DKEC7.png)

**其他说明**

尝试过删除本地所有配置文件重新运行，会产生相同的错误

**Comment by Fndroid** [comment]
你要用tun，把dll下载了么

**Comment by Aceralon** [comment]
应该是这个问题了，之前的Windows版本不支持tun就不会报错🤣

**Comment by Aceralon** [comment]
添加 dll 后的 log 有变化，报错相同

```
2020/12/27 22:42:26 http: panic serving 127.0.0.1:12766: %1 is not a valid Win32 application.
goroutine 35 [running]:
net/http.(*conn).serve.func1(0xc000132000)
	net/http/server.go:1801 +0x147
panic(0x11d3280, 0x173a7e8)
	runtime/panic.go:975 +0x499
golang.org/x/sys/windows.(*LazyProc).mustFind(...)
	golang.org/x/sys@v0.0.0-20201214210602-f9fddec55a1e/windows/dll_windows.go:325
golang.org/x/sys/windows.(*LazyProc).Addr(...)
	golang.org/x/sys@v0.0.0-20201214210602-f9fddec55a1e/windows/dll_windows.go:333
github.com/Dreamacro/clash/proxy/device/wintun.loadDLL.func1()
	github.com/Dreamacro/clash/proxy/device/wintun/wintun.go:58 +0x11e
sync.(*Once).doSlow(0xc000031070, 0x12c05f0)
	sync/once.go:66 +0xf7
sync.(*Once).Do(...)
	sync/once.go:57
github.com/Dreamacro/clash/proxy/device/wintun.loadDLL()
	github.com/Dreamacro/clash/proxy/device/wintun/wintun.go:55 +0x50
github.com/Dreamacro/clash/proxy/device/wintun.MakePool(0x1284163, 0x5, 0xc00004f080, 0xc000155268, 0xa66129)
	github.com/Dreamacro/clash/proxy/device/wintun/wintun.go:66 +0x2d
github.com/Dreamacro/clash/proxy/device.getWinPool.func1()
	github.com/Dreamacro/clash/proxy/device/tun_windows.go:61 +0x45
sync.(*Once).doSlow(0xc000031080, 0x12c05d0)
	sync/once.go:66 +0xf7
sync.(*Once).Do(...)
	sync/once.go:57
github.com/Dreamacro/clash/proxy/device.getWinPool(0xebe71b)
	github.com/Dreamacro/clash/proxy/device/tun_windows.go:59 +0x5c
github.com/Dreamacro/clash/proxy/device.CreateTUNWithRequestedGUID(0x1284163, 0x5, 0xc0001fd690, 0x2328, 0x1, 0x119a7c0, 0x20, 0x20)
	github.com/Dreamacro/clash/proxy/device/tun_windows.go:117 +0x3b
github.com/Dreamacro/clash/proxy/device.CreateTUN(0x1284163, 0x5, 0x2328, 0xc0001553dc, 0x4, 0x4, 0xc0000e6040)
	github.com/Dreamacro/clash/proxy/device/tun_windows.go:106 +0x154
github.com/Dreamacro/clash/proxy/tun.NewTunProxy(0xc0005a15c0, 0xc0005a4ec0, 0x3, 0x4, 0x3, 0xc0005a4ec0, 0x2)
	github.com/Dreamacro/clash/proxy/tun/adapter.go:271 +0xb2
github.com/Dreamacro/clash/proxy.ReCreateTun(0x1, 0xc0005a15c0, 0xc0001fc9c8, 0x6, 0x101, 0x17b9a68, 0x0, 0x0, 0xc0005a4e20, 0x2, ...)
	github.com/Dreamacro/clash/proxy/listener.go:233 +0x5ea
github.com/Dreamacro/clash/hub/executor.updateTun(0xc0000eec00)
	github.com/Dreamacro/clash/hub/executor/executor.go:132 +0x1f8
github.com/Dreamacro/clash/hub/executor.ApplyConfig(0xc0000eec00, 0x1500)
	github.com/Dreamacro/clash/hub/executor/executor.go:73 +0x113
github.com/Dreamacro/clash/hub/route.updateConfigs(0x1374de0, 0xc0000fa380, 0xc0000f4700)
	github.com/Dreamacro/clash/hub/route/configs.go:124 +0x16d
net/http.HandlerFunc.ServeHTTP(0x12c05a0, 0x1374de0, 0xc0000fa380, 0xc0000f4700)
	net/http/server.go:2042 +0x4b
github.com/go-chi/chi.(*Mux).routeHTTP(0xc0002004e0, 0x1374de0, 0xc0000fa380, 0xc0000f4700)
	github.com/go-chi/chi@v4.1.2+incompatible/mux.go:431 +0x28b
net/http.HandlerFunc.ServeHTTP(0xc0002240a0, 0x1374de0, 0xc0000fa380, 0xc0000f4700)
	net/http/server.go:2042 +0x4b
github.com/go-chi/chi.(*Mux).ServeHTTP(0xc0002004e0, 0x1374de0, 0xc0000fa380, 0xc0000f4700)
	github.com/go-chi/chi@v4.1.2+incompatible/mux.go:70 +0x50c
github.com/go-chi/chi.(*Mux).Mount.func1(0x1374de0, 0xc0000fa380, 0xc0000f4700)
	github.com/go-chi/chi@v4.1.2+incompatible/mux.go:298 +0x122
net/http.HandlerFunc.ServeHTTP(0xc0002021e0, 0x1374de0, 0xc0000fa380, 0xc0000f4700)
	net/http/server.go:2042 +0x4b
github.com/Dreamacro/clash/hub/route.authentication.func1(0x1374de0, 0xc0000fa380, 0xc0000f4700)
	github.com/Dreamacro/clash/hub/route/server.go:96 +0x3f3
net/http.HandlerFunc.ServeHTTP(0xc000202200, 0x1374de0, 0xc0000fa380, 0xc0000f4700)
	net/http/server.go:2042 +0x4b
github.com/go-chi/chi.(*ChainHandler).ServeHTTP(0xc000226380, 0x1374de0, 0xc0000fa380, 0xc0000f4700)
	github.com/go-chi/chi@v4.1.2+incompatible/chain.go:31 +0x59
github.com/go-chi/chi.(*Mux).routeHTTP(0xc000200420, 0x1374de0, 0xc0000fa380, 0xc0000f4700)
	github.com/go-chi/chi@v4.1.2+incompatible/mux.go:431 +0x28b
net/http.HandlerFunc.ServeHTTP(0xc000224040, 0x1374de0, 0xc0000fa380, 0xc0000f4700)
	net/http/server.go:2042 +0x4b
github.com/go-chi/cors.(*Cors).Handler.func1(0x1374de0, 0xc0000fa380, 0xc0000f4700)
	github.com/go-chi/cors@v1.1.1/cors.go:228 +0x1c6
net/http.HandlerFunc.ServeHTTP(0xc000202080, 0x1374de0, 0xc0000fa380, 0xc0000f4700)
	net/http/server.go:2042 +0x4b
github.com/go-chi/chi.(*Mux).ServeHTTP(0xc000200420, 0x1374de0, 0xc0000fa380, 0xc000319300)
	github.com/go-chi/chi@v4.1.2+incompatible/mux.go:86 +0x2d1
net/http.serverHandler.ServeHTTP(0xc000254000, 0x1374de0, 0xc0000fa380, 0xc000319300)
	net/http/server.go:2843 +0xaa
net/http.(*conn).serve(0xc000132000, 0x1375f20, 0xc000300300)
	net/http/server.go:1925 +0x8ad
created by net/http.(*Server).Serve
	net/http/server.go:2969 +0x36d
```

相关设置为
```
dns:
  enable: true
  ipv6: false
  use-hosts: true
  nameserver:
    - https://223.5.5.5/dns-query
    - https://223.6.6.6/dns-query
    - https://doh.pub/dns-query
  fallback: []
  fallback-filter:
    geoip: true
    ipcidr: []
  listen: 0.0.0.0:53
  enhanced-mode: redir-host
  fake-ip-range: 198.18.0.1/16
  default-nameserver:
    - 114.114.115.115
    - 119.28.28.28
    - 223.6.6.6
tun:
  enable: true
  stack: gvisor
  dns-hijack:
    - 8.8.8.8:53
    - 8.8.4.4:53
  macOS-auto-route: true
  macOS-auto-detect-interface: true # 自动检测出口网卡
```

**Comment by Fndroid** [comment]
确定没有下错版本么

**Comment by Aceralon** [comment]
wintun 用成了 0.10 的 x86 换成 amd64 的就正常了😅

**Comment by Arisono** [comment]
我用了这个版本之后，就解决了问题。版本：0.17.3
![image](https://user-images.githubusercontent.com/8653027/160355633-45695a53-4988-4bdf-bb7d-e79893e54483.png)
