### ISSUE TITLE
TUN模式无法识别wintun.dll

### ISSUE THREAD

**Issue by yvesyy** [Fndroid/clash_for_windows_pkg#1457]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)
Windows 10 20H2
amd64 (3700X)
wintun 0.10

**描述**

[//]: # (请具体并清楚地描述遇到的问题)
无法切换到profile，提示Network Error （同[#1450](https://github.com/Fndroid/clash_for_windows_pkg/issues/1450)）
根据报错信息(The specified module could not be found.)，应当是没有识别出dll文件。但我检查了文件路径是与Clash for Windows.exe在同一目录，且符合我的arch(3700X, amd64)

**复现**

[//]: # (请描述复现问题的步骤)
1. 进入网站Wintun，复制amd64版wintun.dll至CFW Home Directory目录中
2. 以管理员权限启动 CFW
3. 在使用的配置文件中加入如下内容：
```
dns:
  enable: true
  enhanced-mode: redir-host
  nameserver:
    - 1.1.1.1

tun:
  enable: true
  stack: gvisor
  dns-hijack:
    - 198.18.0.2:53
  macOS-auto-route: true
  macOS-auto-detect-interface: true
```

**预期行为**

[//]: # (清晰地描述期望看到的行为)
正常切换profile

**日志**

[//]: # (上传触发问题对应的日志文件)
```
2020/12/30 14:16:12 http: panic serving 127.0.0.1:59713: The specified module could not be found.
goroutine 135671 [running]:
net/http.(*conn).serve.func1(0xc000434280)
	net/http/server.go:1801 +0x147
panic(0x833280, 0xd9a5d0)
	runtime/panic.go:975 +0x499
golang.org/x/sys/windows.(*LazyProc).mustFind(...)
	golang.org/x/sys@v0.0.0-20201214210602-f9fddec55a1e/windows/dll_windows.go:325
golang.org/x/sys/windows.(*LazyProc).Addr(...)
	golang.org/x/sys@v0.0.0-20201214210602-f9fddec55a1e/windows/dll_windows.go:333
github.com/Dreamacro/clash/proxy/device/wintun.(*Pool).OpenAdapter(0x0, 0x8e4163, 0x5, 0x51e729, 0xc027905700, 0xc03c13f300)
	github.com/Dreamacro/clash/proxy/device/wintun/wintun.go:98 +0x22f
github.com/Dreamacro/clash/proxy/device.CreateTUNWithRequestedGUID(0x8e4163, 0x5, 0xc01b259620, 0x2328, 0x1, 0x7fa7c0, 0x20, 0x20)
	github.com/Dreamacro/clash/proxy/device/tun_windows.go:117 +0x5a
github.com/Dreamacro/clash/proxy/device.CreateTUN(0x8e4163, 0x5, 0x2328, 0xc03c13f3dc, 0x4, 0x4, 0xc00017c040)
	github.com/Dreamacro/clash/proxy/device/tun_windows.go:106 +0x154
github.com/Dreamacro/clash/proxy/tun.NewTunProxy(0xc0229427b0, 0xc0279056e0, 0x3, 0x4, 0x3, 0xc0279056e0, 0x2)
	github.com/Dreamacro/clash/proxy/tun/adapter.go:271 +0xb2
github.com/Dreamacro/clash/proxy.ReCreateTun(0x1, 0xc0229427b0, 0xc014fe3068, 0x6, 0x101, 0xe19a68, 0x0, 0x0, 0xc027905640, 0x2, ...)
	github.com/Dreamacro/clash/proxy/listener.go:233 +0x5ea
github.com/Dreamacro/clash/hub/executor.updateTun(0xc01e63b580)
	github.com/Dreamacro/clash/hub/executor/executor.go:132 +0x1f8
github.com/Dreamacro/clash/hub/executor.ApplyConfig(0xc01e63b580, 0x6e500)
	github.com/Dreamacro/clash/hub/executor/executor.go:73 +0x113
github.com/Dreamacro/clash/hub/route.updateConfigs(0x9d4de0, 0xc0003261c0, 0xc01269c900)
	github.com/Dreamacro/clash/hub/route/configs.go:124 +0x16d
net/http.HandlerFunc.ServeHTTP(0x9205a0, 0x9d4de0, 0xc0003261c0, 0xc01269c900)
	net/http/server.go:2042 +0x4b
github.com/go-chi/chi.(*Mux).routeHTTP(0xc0002286c0, 0x9d4de0, 0xc0003261c0, 0xc01269c900)
	github.com/go-chi/chi@v4.1.2+incompatible/mux.go:431 +0x28b
net/http.HandlerFunc.ServeHTTP(0xc00022e0a0, 0x9d4de0, 0xc0003261c0, 0xc01269c900)
	net/http/server.go:2042 +0x4b
github.com/go-chi/chi.(*Mux).ServeHTTP(0xc0002286c0, 0x9d4de0, 0xc0003261c0, 0xc01269c900)
	github.com/go-chi/chi@v4.1.2+incompatible/mux.go:70 +0x50c
github.com/go-chi/chi.(*Mux).Mount.func1(0x9d4de0, 0xc0003261c0, 0xc01269c900)
	github.com/go-chi/chi@v4.1.2+incompatible/mux.go:298 +0x122
net/http.HandlerFunc.ServeHTTP(0xc0002321c0, 0x9d4de0, 0xc0003261c0, 0xc01269c900)
	net/http/server.go:2042 +0x4b
github.com/Dreamacro/clash/hub/route.authentication.func1(0x9d4de0, 0xc0003261c0, 0xc01269c900)
	github.com/Dreamacro/clash/hub/route/server.go:96 +0x3f3
net/http.HandlerFunc.ServeHTTP(0xc0002321e0, 0x9d4de0, 0xc0003261c0, 0xc01269c900)
	net/http/server.go:2042 +0x4b
github.com/go-chi/chi.(*ChainHandler).ServeHTTP(0xc000234380, 0x9d4de0, 0xc0003261c0, 0xc01269c900)
	github.com/go-chi/chi@v4.1.2+incompatible/chain.go:31 +0x59
github.com/go-chi/chi.(*Mux).routeHTTP(0xc000228600, 0x9d4de0, 0xc0003261c0, 0xc01269c900)
	github.com/go-chi/chi@v4.1.2+incompatible/mux.go:431 +0x28b
net/http.HandlerFunc.ServeHTTP(0xc00022e040, 0x9d4de0, 0xc0003261c0, 0xc01269c900)
	net/http/server.go:2042 +0x4b
github.com/go-chi/cors.(*Cors).Handler.func1(0x9d4de0, 0xc0003261c0, 0xc01269c900)
	github.com/go-chi/cors@v1.1.1/cors.go:228 +0x1c6
net/http.HandlerFunc.ServeHTTP(0xc000232060, 0x9d4de0, 0xc0003261c0, 0xc01269c900)
	net/http/server.go:2042 +0x4b
github.com/go-chi/chi.(*Mux).ServeHTTP(0xc000228600, 0x9d4de0, 0xc0003261c0, 0xc01269c800)
	github.com/go-chi/chi@v4.1.2+incompatible/mux.go:86 +0x2d1
net/http.serverHandler.ServeHTTP(0xc000264000, 0x9d4de0, 0xc0003261c0, 0xc01269c800)
	net/http/server.go:2843 +0xaa
net/http.(*conn).serve(0xc000434280, 0x9d5f20, 0xc0121b73c0)
	net/http/server.go:1925 +0x8ad
created by net/http.(*Server).Serve
	net/http/server.go:2969 +0x36d
```

**截图**

[//]: # (如果可以，请提供对应问题的截图)
![1](https://user-images.githubusercontent.com/44234286/103333924-9df66b00-4aaa-11eb-8c2e-966bde466e2a.PNG)

**其他说明**

[//]: # (其他补充内容)

**Comment by Fndroid** [comment]
![image](https://user-images.githubusercontent.com/16091562/103336302-b074a280-4ab2-11eb-92b3-13056d5ecf08.png)
这个才叫``Home Directory``
