### ISSUE TITLE
0.14.4按照文档中的操作尝试开启TUN模式时service mode无法开启

### ISSUE THREAD

**Issue by Lee-cybererwgft** [Fndroid/clash_for_windows_pkg#1610]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [ √ ] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [ √] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [ √] 已经尝试更新到最新版本，问题依旧存在
- [ √] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[/0.14.4 CFW ，Windows10  X64 ]:

**描述**

[/0.14.4 按照文档中的操作尝试开启TUN模式时service mode无法开启/]: # (请具体并清楚地描述遇到的问题)

**复现**

[//]: # (请描述复现问题的步骤)

1.下载wintun 0.10.1并解压，将arm64 文件夹中的 wintun.dll 拖入Home Directory打开的文件夹中
2. 点击service mode 右侧Manage 并点击Install ，等待半个多小时无反应，软件也未重启，Service Mode 右边地球图标也未变为绿色

**预期行为**

[//]: # (清晰地描述期望看到的行为)

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[/ /]: # (如果可以，请提供对应问题的截图)

**其他说明**

[//]: # (其他补充内容)

**Comment by yi-Xu-0100** [comment]
如果是 64位， 试试 amd64

**Comment by ygsk10** [comment]
```
2021-02-01 15:40:46,660 DEBUG - Starting WinSW in console mode
2021-02-01 15:40:46,718 FATAL - Unhandled exception
System.Management.ManagementException: Generic failure 
   at System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   at System.Management.ManagementObjectCollection.ManagementObjectEnumerator.MoveNext()
   at WMI.WmiRoot.ClassHandler.Invoke(Object proxy, MethodInfo method, Object[] arguments)
   at WMI.IWin32ServicesProxy.Select(String )
   at WinSW.Program.Run(String[] argsArray, IWinSWConfiguration descriptor)
   at WinSW.Program.Main(String[] args)
```
是 winsw 的问题

https://github.com/winsw/winsw/issues/204 和 https://github.com/winsw/winsw/issues/749

按照 [这里](https://social.msdn.microsoft.com/Forums/vstudio/en-US/c98465fe-c40f-4d1f-9654-316e2888069c/systemmanagement-generic-failure?forum=netfxbcl) 的建议重启了 WMI 服务，也没有解决

**Comment by ygsk10** [comment]
#1585

**Comment by zincccccc** [comment]
与楼主出现同样的问题，Win10 64Bit，使用的是amd64的wintun.dll。与另外一台电脑对比后发现，是C:\Users下用户名中英文的问题。如果用户名是中文（即Clash的Home Directory地址中含有中文），则无法启用TUN模式。不知道这算不算是bug。 @Fndroid

**Comment by yi-Xu-0100** [comment]
@zincccccc  https://github.com/Fndroid/clash_for_windows_pkg/issues/1610#issuecomment-777230789 建议修改用户名为英文，一劳永逸

**Comment by ygsk10** [comment]
> @zincccccc [#1610 (comment)](https://github.com/Fndroid/clash_for_windows_pkg/issues/1610#issuecomment-777230789) 建议修改用户名为英文，一劳永逸

修改用户名为英文之后 C:\Users 下的文件夹名不会变


> 与楼主出现同样的问题，Win10 64Bit，使用的是amd64的wintun.dll。与另外一台电脑对比后发现，是C:\Users下用户名中英文的问题。如果用户名是中文（即Clash的Home Directory地址中含有中文），则无法启用TUN模式。不知道这算不算是bug。 @Fndroid

能否发一下 service/*.log 的内容

**Comment by zincccccc** [comment]
> > 与楼主出现同样的问题，Win10 64Bit，使用的是amd64的wintun.dll。与另外一台电脑对比后发现，是C:\Users下用户名中英文的问题。如果用户名是中文（即Clash的Home Directory地址中含有中文），则无法启用TUN模式。不知道这算不算是bug。 @Fndroid
> 
> 能否发一下无法启用时 `Home Directory/service/service.wrapper.log` 的内容

目录下没有 service.wrapper.log 这个文件噢

**Comment by ygsk10** [comment]
> @ygsk10 https://www.zhihu.com/question/37082172 ，建议自行测试，注意数据安全

最近就修改过一次，文件夹名确实不会变的。

请看一下文档中的 Workaround

在 [docs.microsoft.com](https://docs.microsoft.com/en-US/troubleshoot/windows-client/user-profiles-and-logon/renaming-user-account-not-change-profile-path)

**Comment by yi-Xu-0100** [comment]
@ygsk10 

> Go to the C:\users\ folder and rename the sub folder with the original user name to the new user name.

他不是让你自己重命名了吗？

**Comment by QianHong** [comment]
15.1版本遇到同样的错误，用户名也是英文 。
2021-04-01 17:44:16,961 DEBUG - Starting WinSW in service mode
2021-04-01 17:44:18,434 DEBUG - Completed. Exit code is 0
2021-04-01 17:45:42,864 DEBUG - Starting WinSW in console mode
2021-04-01 17:45:43,267 INFO  - Installing the service with id 'Clash Core Service'
2021-04-01 17:45:43,278 FATAL - WMI Operation failure: UnknownFailure
WMI.WmiException: UnknownFailure
   在 WMI.WmiRoot.BaseHandler.CheckError(ManagementBaseObject result)
   在 WMI.WmiRoot.ClassHandler.Invoke(Object proxy, MethodInfo method, Object[] arguments)
   在 WinSW.Program.<Run>g__Install|2_0(<>c__DisplayClass2_0& )
   在 WinSW.Program.Run(String[] argsArray, IWinSWConfiguration descriptor)
   在 WinSW.Program.Main(String[] args)
2021-04-01 17:45:43,511 DEBUG - Starting WinSW in console mode
2021-04-01 17:45:43,891 INFO  - Starting the service with id 'Clash Core Service'
2021-04-01 17:45:43,892 FATAL - WMI Operation failure: NoSuchService
WMI.WmiException: NoSuchService
   在 WinSW.Program.ThrowNoSuchService()
   在 WinSW.Program.<Run>g__Start|2_2(<>c__DisplayClass2_0& )
   在 WinSW.Program.Run(String[] argsArray, IWinSWConfiguration descriptor)
   在 WinSW.Program.Main(String[] args)
2021-04-01 17:46:54,857 DEBUG - Starting WinSW in console mode
2021-04-01 17:46:55,258 INFO  - Installing the service with id 'Clash Core Service'
2021-04-01 17:46:55,269 FATAL - WMI Operation failure: UnknownFailure
WMI.WmiException: UnknownFailure
   在 WMI.WmiRoot.BaseHandler.CheckError(ManagementBaseObject result)
   在 WMI.WmiRoot.ClassHandler.Invoke(Object proxy, MethodInfo method, Object[] arguments)
   在 WinSW.Program.<Run>g__Install|2_0(<>c__DisplayClass2_0& )
   在 WinSW.Program.Run(String[] argsArray, IWinSWConfiguration descriptor)
   在 WinSW.Program.Main(String[] args)
2021-04-01 17:46:55,505 DEBUG - Starting WinSW in console mode
2021-04-01 17:46:55,898 INFO  - Starting the service with id 'Clash Core Service'
2021-04-01 17:46:55,899 FATAL - WMI Operation failure: NoSuchService
WMI.WmiException: NoSuchService
   在 WinSW.Program.ThrowNoSuchService()
   在 WinSW.Program.<Run>g__Start|2_2(<>c__DisplayClass2_0& )
   在 WinSW.Program.Run(String[] argsArray, IWinSWConfiguration descriptor)
   在 WinSW.Program.Main(String[] args)
求解

**Comment by Fndroid** [comment]
This issue is stale because it has been open 60 days with no activity. Remove stale label or comment or this will be closed in 7 days
