### ISSUE TITLE
clash_for_windows_pkg 0.15.5版本在使用一段时间后UI卡住，核心代理功能也失效

### ISSUE THREAD

**Issue by zxhpipi** [Fndroid/clash_for_windows_pkg#1863]
[//]: # (如不按模版填写，则issue将被直接关闭)

clash_for_windows_pkg 0.15.5版本在使用一段时间后UI卡住，核心代理功能也失效

[//]: # (如果符合，请将``[ ]``改为``[x]``)

- [X ] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [X ] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [X ] 已经尝试更新到最新版本，问题依旧存在
- [ X] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # (平台及版本号)

系统win10 20H2

[//]: # (请具体并清楚地描述遇到的问题)

使用一段时间后UI界面的流量显示卡住不动，核心代理功能也失效。

**日志**

panic: runtime error: slice bounds out of range [:5544] with capacity 4096

goroutine 829 [running]:
bufio.(*Reader).Read(0xc000200ea0, 0xc00003224c, 0x2, 0x2, 0xc000373b20, 0xe0fc8a, 0xc0004122c0)
	bufio/bufio.go:238 +0x3da
github.com/gorilla/websocket.(*messageReader).Read(0xc0003efc90, 0xc00003224c, 0x2, 0x2, 0x0, 0x134a0a0, 0xc000058070)
	github.com/gorilla/websocket@v1.4.2/conn.go:1021 +0x1fa
github.com/Dreamacro/clash/component/vmess.(*websocketConn).Read(0xc000096380, 0xc00003224c, 0x2, 0x2, 0x0, 0x0, 0x0)
	github.com/Dreamacro/clash/component/vmess/websocket.go:48 +0xe4
io.ReadAtLeast(0x16170789b90, 0xc000096380, 0xc00003224c, 0x2, 0x2, 0x2, 0xacdd87, 0xc000254c80, 0x128f3d8)
	io/io.go:328 +0x8e
io.ReadFull(...)
	io/io.go:347
github.com/Dreamacro/clash/component/vmess.(*aeadReader).Read(0xc00007cdc0, 0xc000626000, 0x5000, 0x8000, 0xc000373d80, 0xb17935, 0xc000254c80)
	github.com/Dreamacro/clash/component/vmess/aead.go:82 +0x1b2
github.com/Dreamacro/clash/component/vmess.(*Conn).Read(0xc0003dc000, 0xc000626000, 0x5000, 0x8000, 0x2000, 0x0, 0x0)
	github.com/Dreamacro/clash/component/vmess/conn.go:49 +0x108
github.com/Dreamacro/clash/tunnel/statistic.(*tcpTracker).Read(0xc00011e100, 0xc000626000, 0x5000, 0x8000, 0x2000, 0x0, 0x0)
	github.com/Dreamacro/clash/tunnel/statistic/tracker.go:40 +0x5c
io.copyBuffer(0x134bb40, 0xc0003da280, 0x134bb20, 0xc0003da290, 0xc000626000, 0x5000, 0x8000, 0xc0003da290, 0xc0003da290, 0x119b020)
	io/io.go:423 +0x12c
io.CopyBuffer(0x134bb40, 0xc0003da280, 0x134bb20, 0xc0003da290, 0xc000626000, 0x5000, 0x8000, 0xc000200cc0, 0xc000373f98, 0x161698e1301)
	io/io.go:396 +0x89
github.com/Dreamacro/clash/tunnel.relay.func1(0x135f620, 0xc000410828, 0x1616ece4090, 0xc00011e100, 0xc000030300)
	github.com/Dreamacro/clash/tunnel/connection.go:154 +0x19b
created by github.com/Dreamacro/clash/tunnel.relay
	github.com/Dreamacro/clash/tunnel/connection.go:150 +0xaa

**Comment by yi-Xu-0100** [comment]
看起来像是：core issue: <https://github.com/Dreamacro/clash/issues>
