### ISSUE TITLE
更新至0.16.2后主页面显示Loading...

### ISSUE THREAD

**Issue by LimJacheon** [Fndroid/clash_for_windows_pkg#2026]
[//]: # (如不按模版填写，则issue将被直接关闭)

**信息**

[//]: # 

- [x] 已经从[issue](https://github.com/Fndroid/clash_for_windows_pkg/issues)搜索过类似问题，并未发现重复
- [x] 已经阅读过[文档](https://docs.cfw.lbyczf.com/)相关问题，并未找到解决办法
- [x] 已经尝试更新到最新版本，问题依旧存在
- [x] 软件从本仓库下载，并非任何非官方版本（包括任何替换软件目录文件操作）

**系统**

[//]: # Win10 21H1
**描述**

[//]: # 在更新Clash 0.16.2 以后主页面 显示为"Loading..."
**复现**

[//]: # 1. 进入Clash0.16.1发现提示有更新
2. 点击 版本号 进行新版本的更新
3. 版本自动更新至0.16.2'
4. 触发问题

**预期行为**

[//]: # (清晰地描述期望看到的行为) 因为使用0.16.1乃至之前的版本并没有出现这种情况 所以希望 0.16.2 可以也正常使用

**日志**

[//]: # (上传触发问题对应的日志文件)

**截图**

[//]: # 
![image](https://user-images.githubusercontent.com/87220981/125154457-ba2b4100-e18c-11eb-9048-d28fdfd798b4.png)

**其他说明**

[//]: # 首先第一次更新后出现Loading... 我以为是安装包的问题 故卸载重装 发现此问题 依然存在 然后我在另一台Win7的电脑上安装Clash 0.16.2发现可以正常使用 因为Win7系统 可以正常使用 我又进行了重装两次系统 发现在重装系统以后 安装Clash 0.16.2 是可以正常使用的 但是 只要关机、重新启动 以后 再次打开Clash 又会变为 Loading...

**Comment by Fndroid** [comment]
有出现问题时候的日志吗

**Comment by wtgj** [comment]
I have the same problem. It can be used once after reinstalling clash. This problem occurs whenever I restart the computer or sleep. After selecting the profile, a network error will be prompted.
OS:Win10 Pro 21H1

**Comment by wtgj** [comment]
I have reverted to the previous version and there is no problem.

**Comment by LimJacheon** [comment]
Ummm首先很是抱歉 由于我第一次出现这种情况 而且设定都是默认 所以我并不知道如何查看日志... 如果您能告知 我可以进行查看并上传 万分感谢...  另外 我目前已经恢复至16.0.1 可以正常使用

**Comment by LimJacheon** [comment]
更新：可能由于0.16.2 主页面一直处于加载中的原因？ 日志内无任何信息点击Start 无任何响应 在Clash 0.16.2运行的过程中 无法打开baidu.com... 以下是截图
<img width="1591" alt="20210710153201" src="https://user-images.githubusercontent.com/87220981/125155794-c1eee380-e194-11eb-9d3a-e08da232e518.png">

**Comment by Fndroid** [comment]
先退回上一版吧

**Comment by LimJacheon** [comment]
> 先退回上一版吧
好的 感谢您对于此问题的关注与回复 谢谢

**Comment by CberYellowstone** [comment]
出现此问题+1

**Comment by wtgj** [comment]
mac版沒有問題，已在10.15上測試。

**Comment by wtgj** [comment]
windows版日誌無法抓取，點擊按鈕沒有任何反應。

**Comment by Wisil** [comment]
我也遇到同样问题，有时候也会正常，时好时坏

**Comment by bohong666** [comment]
出现同样问题！ loading.......

**Comment by leafsoul365** [comment]
+1，这里也是同样的问题，重启电脑-自动启动clash，主页面显示  loading.......，无法正常使用。

**Comment by 00lingsui** [comment]
Win11. 21H2 .22000.65也遇到了这个问题

**Comment by kerry64** [comment]
日志如下：
```

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x58 pc=0x130ac4e]

goroutine 25 [running]:
github.com/Dreamacro/clash/tunnel.resolveMetadata.func1(0xc00022dd98, 0x1602db0, 0x1a8c828, 0xc00022dd88, 0xc00022dd78, 0xc000204280)
	github.com/Dreamacro/clash/tunnel/tunnel.go:190 +0x8e
github.com/Dreamacro/clash/tunnel.resolveMetadata(0x2b3ffdd53b8, 0xc000231080, 0xc000204280, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	github.com/Dreamacro/clash/tunnel/tunnel.go:209 +0x225
github.com/Dreamacro/clash/tunnel.handleTCPConn(0x1602e20, 0xc000231080)
	github.com/Dreamacro/clash/tunnel/tunnel.go:358 +0x1ca
created by github.com/Dreamacro/clash/tunnel.process
	github.com/Dreamacro/clash/tunnel/tunnel.go:135 +0xc5

```

**Comment by wtgj** [comment]
After updating to the latest version, the problem has been resolved.

**Comment by LimJacheon** [comment]
更新0.16.3后 问题已经得到解决

**Comment by chinyu0704** [comment]
> 更新0.16.3后 问题已经得到解决

no the problem is not fixed yet.
![image](https://user-images.githubusercontent.com/19435140/126036493-69b20892-57fe-4a77-922c-a04e4c623062.png)

**Comment by Lat0ur** [comment]
![S{QB)$CR}VP$NU64(X9RS9T](https://user-images.githubusercontent.com/9115509/126054149-11a79e87-625f-4d74-b8c9-8cb4aaf83233.png)the log files

**Comment by yi-Xu-0100** [comment]
@Lat0ur 你这看起来是 provider 出问题了，建议检查 provider 直连是否可行

**Comment by chinyu0704** [comment]
@Fndroid 我觉得我找到了一个可能影响的因素：当使能win 10 sandbox（沙盒）特性以后，会出现上述问题；再次禁用以后就恢复正常。我猜这里面应该有冲突

**Comment by leafsoul365** [comment]
0.16.3 依旧会概率性出现这个问题。当电脑重启，依旧有概率卡在loading界面。虽然多数情况可能不会。已经碰到两次了。

**Comment by PjOnE7** [comment]
> 先退回上一版吧

你好，请问有解决办法了吗，我更新到了0.17还是无法解决

**Comment by Lat0ur** [comment]
我重装系统就好了------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年8月4日(星期三) 中午12:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Fndroid/clash_for_windows_pkg] 更新至0.16.2后主页面显示Loading... (#2026)

**Comment by PjOnE7** [comment]
> 我重装系统就好了------------------&nbsp;原始邮件&nbsp;------------------ ***@***.***&gt; 发送时间:&nbsp;2021年8月4日(星期三) 中午12:28 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [Fndroid/clash_for_windows_pkg] 更新至0.16.2后主页面显示Loading... (#2026)

啊 要重装系统这么夸张嘛

**Comment by weiqiyang** [comment]
I am having the same problem with v0.17.2
![temp](https://user-images.githubusercontent.com/3526294/131207779-bf6e2e83-ca5e-443c-bb5d-439806111289.png)
![temp1](https://user-images.githubusercontent.com/3526294/131207780-a6068876-9ed4-48d1-8c87-5ce5c86960c5.png)

**Comment by kaaass** [comment]
相同问题发生于 21H1 19043.1237。在从 2020 年的旧版本切换至 0.18.2 后发生了一次系统崩溃，重启后即出现上述情况。
最终回退至 0.14.4 解决问题。

**Comment by Exlancer** [comment]
win21H1，出现同样的问题，对任何一个配置文件（包括自动生成的config.yaml）都显示Could not switch to this profile，General卡Loading。

Log文件显示
![image](https://user-images.githubusercontent.com/16717945/140615116-741e2014-85df-46b0-8c49-167158a1ddae.png)

尝试了大部分措施，包括更换amd64的tun.dll、删除administrator下的config文件夹后重启/重装、回退版本（从18版回退到14版）、更改DNS、给程序提供防火墙权限。

**Comment by yi-Xu-0100** [comment]
@Exlancer
 > 删除administrator下的config文件夹后

你是不是删错了

**Comment by Exlancer** [comment]
> @Exlancer
> 
> > 删除administrator下的config文件夹后
> 
> 你是不是删错了

没有，这里是我打错了，删除的就是/Users/<用户名>/.config/clash文件夹。

**Comment by yi-Xu-0100** [comment]
@Exlancer logs 里的内容有吗？

**Comment by Exlancer** [comment]
time="2021-11-06T23:16:06+08:00" level=info msg="Mixed(http+socks) proxy listening at: 127.0.0.1:7890"
time="2021-11-06T23:16:06+08:00" level=info msg="RESTful API listening at: 127.0.0.1:65235"

time="2021-11-06T23:21:39+08:00" level=info msg="Mixed(http+socks) proxy listening at: 127.0.0.1:7890"
time="2021-11-06T23:21:39+08:00" level=info msg="RESTful API listening at: 127.0.0.1:52766"
↑这是.config-clash-logs里两个log的内容。

time="Sat Nov 06 2021 23:50:29 GMT+0800 (香港标准时间)" level=info msg="app start with mode: production"
time="Sat Nov 06 2021 23:50:29 GMT+0800 (香港标准时间)" level=info msg="http server started at: 65529"
time="Sat Nov 06 2021 23:50:29 GMT+0800 (香港标准时间)" level=info msg="load data from general config.yaml"
time="Sat Nov 06 2021 23:50:29 GMT+0800 (香港标准时间)" level=info msg="mixed-port changed"
time="Sat Nov 06 2021 23:50:29 GMT+0800 (香港标准时间)" level=info msg="external controller port changed"
time="Sat Nov 06 2021 23:50:29 GMT+0800 (香港标准时间)" level=info msg="clash axios client changed"
time="Sat Nov 06 2021 23:50:29 GMT+0800 (香港标准时间)" level=info msg="external controller port changed"
time="Sat Nov 06 2021 23:50:29 GMT+0800 (香港标准时间)" level=info msg="clash axios client changed"
time="Sat Nov 06 2021 23:50:30 GMT+0800 (香港标准时间)" level=info msg="restarting clash core..."
time="Sat Nov 06 2021 23:50:30 GMT+0800 (香港标准时间)" level=info msg="check for app update, current: 0.18.7"
time="Sat Nov 06 2021 23:50:30 GMT+0800 (香港标准时间)" level=info msg="clash core startup success!"
time="Sat Nov 06 2021 23:50:43 GMT+0800 (香港标准时间)" level=info msg="restore at index: 1"
time="Sat Nov 06 2021 23:50:51 GMT+0800 (香港标准时间)" level=warn msg="fail to restore last profile with error: Error: Network Error"

clash菜单打开的logs的内容↑

@yi-Xu-0100

**Comment by yi-Xu-0100** [comment]
@Exlancer https://github.com/Fndroid/clash_for_windows_pkg/issues/442#issuecomment-670994637 试试这个吧，其他的我也不知道

**Comment by Exlancer** [comment]
> @Exlancer [#442 (comment)](https://github.com/Fndroid/clash_for_windows_pkg/issues/442#issuecomment-670994637) 试试这个吧，其他的我也不知道

感谢回复，但应该不是这个情况，表现完全不一样，而且按里面操作之后也没有任何改变。

**Comment by Exlancer** [comment]
最后更新一下，解决了。

直接原因是更新了系统，虽然是一个非常小的累积更新（仅仅“更新操作系统Windows的安全性”的KB5006670）。上面有人说是win10沙盒机制，还不能确定，但基本可以确定这个问题和Windows 10 系统的某个机制有关。

**Comment by chiihc** [comment]
0.18.7也遇到了,更新0.19.0后还是这样,win11

**Comment by jayzhou14** [comment]
> 相同问题发生于 21H1 19043.1237。在从 2020 年的旧版本切换至 0.18.2 后发生了一次系统崩溃，重启后即出现上述情况。 最终回退至 0.14.4 解决问题。

同样遇到这问题，退回0.14.4版本有效

**Comment by Steven-nagisa-Y** [comment]
我从v0.19.1更新后就出现这个问题。但是重启系统后正常。

**Comment by ChitaGideon** [comment]
我也是这个问题。 最新0.18

> I am having the same problem with v0.17.2 ![temp](https://user-images.githubusercontent.com/3526294/131207779-bf6e2e83-ca5e-443c-bb5d-439806111289.png) ![temp1](https://user-images.githubusercontent.com/3526294/131207780-a6068876-9ed4-48d1-8c87-5ce5c86960c5.png)

我在 #1930 留了我的控制台日志：

https://github.com/Fndroid/clash_for_windows_pkg/issues/1930#issuecomment-1037044189

**Comment by Fndroid** [comment]
This issue is stale because it has been open 60 days with no activity. Remove stale label or comment or this will be closed in 7 days
