### ISSUE TITLE
[BUG]: 使用代理时会触发SSL错误

### ISSUE THREAD

**Issue by zxc7895531** [Fndroid/clash_for_windows_pkg#2681]
BUG内容：
使用Python3的requests库请求https地址时会发生SSL错误

Traceback (most recent call last):
  File "test.py", line 44, in <module>
    access_token: str = get_access_token()
  File "test.py", line 9, in get_access_token
    req = requests.get("https://XXXX.com")
  File "C:\Users\Little_C\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\Little_C\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Little_C\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Little_C\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Little_C\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='XXXX.com', port=443): Max retries exceeded with url: XXXX (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))

触发方法：
打开SystemProxy，使用Python3的requests库访问https网页

日志：
日之内无特殊内容，无报错

**Comment by zxc7895531** [comment]
很抱歉没用模板，但是不知为何，我使用了模板Github会400

**Comment by yi-Xu-0100** [comment]
setting 中打开 special protocol

**Comment by YamMangoTea** [comment]
> setting 中打开 special protocol

有效果的！

**Comment by dreamerlzl** [comment]
> setting 中打开 special protocol
linux的cfw在settings页面中没找到有special protocol，版本0.19.23

**Comment by yi-Xu-0100** [comment]
@dreamerlzl 因为这是 windows 的代理设置问题，如果 linux 出现问题，建议给出新的 报错信息，并开个 issue 提问

**Comment by jiayezi** [comment]
我在csdn上找到了另一种解决方式：https://blog.csdn.net/big__banana/article/details/123873178
经测试，也有效果。
`import requests
url = 'https://youtube.com'
headers = {'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36'}
proxy = {'http': '127.0.0.1:7890', 'https': '127.0.0.1:7890'}
response = requests.get(url, headers=headers, proxies=proxy)
response.encoding = 'utf-8'
content = response.text
print(content)`

**Comment by verigle** [comment]
#4043 

@yi-Xu-0100 我在linux 下遇到了SSL error 的问题，但linux的cfw在settings页面中没找到有special protocol
