### ISSUE TITLE
Mac 电脑端 clash for mac通过 clash api使用 http://127.0.0.1:9090/proxies/Proxy 切换代理正常，但同样的代码 在clash for windows 切换错误

### ISSUE THREAD

**Issue by jackwan990** [Fndroid/clash_for_windows_pkg#3265]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

clash for windows v0.19.10

### 操作系统

Windows x64

### 系统版本

Windows 10 教育版

### 问题描述

Mac 电脑端 通过 clash api使用 http://127.0.0.1:9090/proxies/Proxy 切换代理正常，但同样的代码 在clash for windows 下进行
clash api使用 http://127.0.0.1:9090/proxies/Proxy 切换代理错误[Bug]

`Traceback (most recent call last):
File "C:\Users\macbookpro\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
conn = connection.create_connection(
File "C:\Users\macbookpro\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
raise err
File "C:\Users\macbookpro\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
sock.connect(sa)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\macbookpro\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
httplib_response = self._make_request(
File "C:\Users\macbookpro\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 398, in _make_request
conn.request(method, url, **httplib_request_kw)
File "C:\Users\macbookpro\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 239, in request
super(HTTPConnection, self).request(method, url, body=body, headers=headers)
File "C:\Users\macbookpro\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1285, in request
self._send_request(method, url, body, headers, encode_chunked)
File "C:\Users\macbookpro\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1331, in _send_request
self.endheaders(body, encode_chunked=encode_chunked)
File "C:\Users\macbookpro\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1280, in endheaders
self._send_output(message_body, encode_chunked=encode_chunked)
File "C:\Users\macbookpro\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1040, in _send_output
self.send(msg)
File "C:\Users\macbookpro\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 980, in send
self.connect()
File "C:\Users\macbookpro\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 205, in connect
conn = self._new_conn()
File "C:\Users\macbookpro\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000001557C7E0520>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\macbookpro\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 440, in send
resp = conn.urlopen(
File "C:\Users\macbookpro\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 785, in urlopen
retries = retries.increment(
File "C:\Users\macbookpro\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\retry.py", line 592, in increment
raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=9090): Max retries exceeded with url: /proxies/Proxy/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001557C7E0520>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\macbookpro\Desktop\Twiiter\Twiiterv3 带切换代理\Twiiter\proxy.py", line 103, in
print(pr.get_all_proxy())
File "C:\Users\macbookpro\Desktop\Twiiter\Twiiterv3 带切换代理\Twiiter\proxy.py", line 76, in get_all_proxy
response = requests.get('http://127.0.0.1:9090/proxies/Proxy/',headers=Proxy.headers)
File "C:\Users\macbookpro\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 75, in get
return request('get', url, params=params, **kwargs)
File "C:\Users\macbookpro\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 61, in request
return session.request(method=method, url=url, **kwargs)
File "C:\Users\macbookpro\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 529, in request
resp = self.send(prep, **send_kwargs)
File "C:\Users\macbookpro\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 645, in send
r = adapter.send(request, **kwargs)
File "C:\Users\macbookpro\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 519, in send
raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=9090): Max retries exceeded with url: /proxies/Proxy/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001557C7E0520>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
[Finished in 2.9s]`

### 复现步骤

通过clash api使用 http://127.0.0.1:9090/proxies/Proxy 切换代理

python 代码切换
步骤1:通过requests.get进行代理切换如下运行如下
response = requests.get('http://127.0.0.1:9090/proxies/Proxy/') 

然后返回报错信息，反馈回来的信息就是

`Traceback (most recent call last):
File "C:\Users\macbookpro\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
conn = connection.create_connection(
File "C:\Users\macbookpro\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
raise err
File "C:\Users\macbookpro\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
sock.connect(sa)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```
[2022-07-27-234303.log](https://github.com/Fndroid/clash_for_windows_pkg/files/9204894/2022-07-27-234303.log)

</p></details>

**Comment by yi-Xu-0100** [comment]
1. 确认下 CFW 有没有将控制端口更改。
![图片](https://user-images.githubusercontent.com/25523606/181411533-15c805fc-d94f-4f86-89a3-060d7f4127b4.png)

2. 检查 core secret 设置，具体内容在 home directory 的 config.yaml 中查看。

![图片](https://user-images.githubusercontent.com/25523606/181411640-b12f2beb-bf0c-4951-be9c-58128108a53b.png)

**Comment by jackwan990** [comment]
非常感谢！
	刚刚通过clash core进去后，发现端口不是设置的9090，然后每次都会发生变化。

是不是要设置中关闭 Random Controller Port 才行？

**Comment by yi-Xu-0100** [comment]
@jackwan990 是的，默认是 random 。

**Comment by jackwan990** [comment]
非常感谢，经过你的指导，目前问题已经解决。非常感谢！
