### ISSUE TITLE
[Bug]: Errors while trying to do requests with python

### ISSUE THREAD

**Issue by thomashirtz** [Fndroid/clash_for_windows_pkg#3592]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.19.24

### 操作系统

Windows x64

### 系统版本

21H1

### 问题描述

I am trying to do requests with python with a code similar to this one:

```python
import requests

word = '问题'
query = f'https://tatoeba.org/en/api_v0/search?from=cmn&query="{word}"&to=eng'
response = requests.get(url=query)
```

However I get the error :

```
Traceback (most recent call last):
  File "D:\Thomas\GitHub\chinese-card-generator\venv\lib\site-packages\urllib3\connectionpool.py", line 700, in urlopen
    self._prepare_proxy(conn)
  File "D:\Thomas\GitHub\chinese-card-generator\venv\lib\site-packages\urllib3\connectionpool.py", line 996, in _prepare_proxy
    conn.connect()
  File "D:\Thomas\GitHub\chinese-card-generator\venv\lib\site-packages\urllib3\connection.py", line 364, in connect
    self.sock = conn = self._connect_tls_proxy(hostname, conn)
  File "D:\Thomas\GitHub\chinese-card-generator\venv\lib\site-packages\urllib3\connection.py", line 499, in _connect_tls_proxy
    socket = ssl_wrap_socket(
  File "D:\Thomas\GitHub\chinese-card-generator\venv\lib\site-packages\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "D:\Thomas\GitHub\chinese-card-generator\venv\lib\site-packages\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "C:\ProgramData\Anaconda3\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\ProgramData\Anaconda3\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\ProgramData\Anaconda3\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1125)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Thomas\GitHub\chinese-card-generator\venv\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "D:\Thomas\GitHub\chinese-card-generator\venv\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "D:\Thomas\GitHub\chinese-card-generator\venv\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='tatoeba.org', port=443): Max retries exceeded with url: /en/api_v0/search?from=cmn&query=%22%E9%97%AE%E9%A2%98%22&to=eng (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1125)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/Thomas/GitHub/chinese-card-generator/chinese_card_generator/bka.py", line 8, in <module>
    response = requests.get(url=query)
  File "D:\Thomas\GitHub\chinese-card-generator\venv\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "D:\Thomas\GitHub\chinese-card-generator\venv\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Thomas\GitHub\chinese-card-generator\venv\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Thomas\GitHub\chinese-card-generator\venv\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "D:\Thomas\GitHub\chinese-card-generator\venv\lib\site-packages\requests\adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='tatoeba.org', port=443): Max retries exceeded with url: /en/api_v0/search?from=cmn&query=%22%E9%97%AE%E9%A2%98%22&to=eng (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1125)')))

Process finished with exit code 1
```

I tried to use the [proxy](https://stackoverflow.com/questions/8287628/proxies-with-python-requests-module) option, but I couldn't make it work

```python
http_proxy = "http://127.0.0.1:7890"
https_proxy = "https://127.0.0.1:7890"
ftp_proxy = "ftp://127.0.0.1:7890"
```

Does someone know how to do request with clash in the background ?

### 复现步骤

run the snippet :

```python
import requests

word = '问题'
query = f'https://tatoeba.org/en/api_v0/search?from=cmn&query="{word}"&to=eng'
response = requests.get(url=query)
```

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by yi-Xu-0100** [comment]
setting - System Proxy - Specify Protocol

ref:
- #1787

**Comment by thomashirtz** [comment]
Seems to work !

I see that there is a warning "violate the current spec of windows". What does that means, do you have a reference for that as well ? sounds quite bad

**Comment by yi-Xu-0100** [comment]
The reference issue (https://github.com/Fndroid/clash_for_windows_pkg/issues/1787) has detail discussion about it.
