### ISSUE TITLE
[Bug]: Linux 下开启clash 后，python urllib3联网会出现SSLError

### ISSUE THREAD

**Issue by verigle** [Fndroid/clash_for_windows_pkg#4043]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.10

### 操作系统

Linux

### 系统版本

Ubuntu 22.04

### 问题描述

linux 下开启Clash 后，使用python urllib3联网后会出现SSLError

### 复现步骤

linux 下开启Clash
开启TUN 模式
使用python 中的urllib3 这个库联网下载文件时，会出现(Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))

### 日志文件

Traceback (most recent call last):
  File "/home/verigle/miniconda3/envs/lavis/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/verigle/miniconda3/envs/lavis/lib/python3.8/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/home/verigle/miniconda3/envs/lavis/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/home/verigle/miniconda3/envs/lavis/lib/python3.8/site-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/home/verigle/miniconda3/envs/lavis/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/home/verigle/miniconda3/envs/lavis/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/home/verigle/miniconda3/envs/lavis/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/home/verigle/miniconda3/envs/lavis/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/home/verigle/miniconda3/envs/lavis/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/verigle/miniconda3/envs/lavis/lib/python3.8/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/home/verigle/miniconda3/envs/lavis/lib/python3.8/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/home/verigle/miniconda3/envs/lavis/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /bert-base-uncased/resolve/main/vocab.txt (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))

**Comment by yi-Xu-0100** [comment]
尝试开启 setting->System proxy->Sepcify Protocol

**Comment by yi-Xu-0100** [comment]
@verigle 没注意是 linux ，是否有日志提供， CFW 的。

**Comment by verigle** [comment]
请问linux 下日志在哪里查看呢？

**Comment by verigle** [comment]
我找到一片博客，https://blog.csdn.net/CoolBoySilverBullet/article/details/123820008
“CFW 在配置代理服务器时，仅仅给出了地址和端口，并没有给出 入口协议“
不知道对你们排查问题有没有帮助？

**Comment by yi-Xu-0100** [comment]
@verigle 不太清楚了

**Comment by Fndroid** [comment]
This issue is stale because it has been open 60 days with no activity. Remove stale label or comment or this will be closed in 7 days
