### ISSUE TITLE
连一会就断网现实Cant connecto to clash core

### ISSUE THREAD

**Issue by a936838** [Fndroid/clash_for_windows_pkg#435]
[2020-02-18-150756.log](https://github.com/Fndroid/clash_for_windows_pkg/files/4217913/2020-02-18-150756.log)
![image](https://user-images.githubusercontent.com/61180581/74713741-289ff400-5264-11ea-84a2-890bebdc3414.png)
试了8.11和8.10都这样 求助大佬应该怎么解决 我是小白

**Comment by a936838** [comment]
[2020-02-18-153852.log](https://github.com/Fndroid/clash_for_windows_pkg/files/4217946/2020-02-18-153852.log)

**Comment by a936838** [comment]
现在彻底连不上了 点try to repair也没用，连不上core

**Comment by nb5p** [comment]
@a936838 有测试其他配置文件能否正常吗？

panic: runtime error: slice bounds out of range [2030:1120] 
上面这个错误看起来像是内核的问题

**Comment by a936838** [comment]
国外媒体[🇭🇰 香港HKT-10G(8)]"
time="2020-02-20T17:10:19+08:00" level=info msg="[TCP] 127.0.0.1:52893 --> sb.scorecardresearch.com match DomainSuffix using 🛑 全球拦截[REJECT]"
time="2020-02-20T17:10:19+08:00" level=info msg="[TCP] 127.0.0.1:52894 --> sb.scorecardresearch.com match DomainSuffix using 🛑 全球拦截[REJECT]"
time="2020-02-20T17:10:29+08:00" level=info msg="[TCP] 127.0.0.1:52899 --> sb.scorecardresearch.com match DomainSuffix using 🛑 全球拦截[REJECT]"
time="2020-02-20T17:10:39+08:00" level=info msg="[TCP] 127.0.0.1:52904 --> sb.scorecardresearch.com match DomainSuffix using 🛑 全球拦截[REJECT]"
time="2020-02-20T17:10:49+08:00" level=info msg="[TCP] 127.0.0.1:52910 --> sb.scorecardresearch.com match DomainSuffix using 🛑 全球拦截[REJECT]"
time="2020-02-20T17:10:53+08:00" level=info msg="[TCP] 127.0.0.1:52913 --> clients4.google.com match DomainKeyword using 🔰 节点选择[🇭🇰 香港HKT-10G(8)]"
time="2020-02-20T17:10:59+08:00" level=info msg="[TCP] 127.0.0.1:52917 --> sb.scorecardresearch.com match DomainSuffix using 🛑 全球拦截[REJECT]"
time="2020-02-20T17:11:09+08:00" level=info msg="[TCP] 127.0.0.1:52921 --> sb.scorecardresearch.com match DomainSuffix using 🛑 全球拦截[REJECT]"
panic: runtime error: slice bounds out of range [2030:76]

goroutine 788 [running]:
internal/poll.(*FD).Write(0xc00013ef00, 0xc00089b000, 0x4c, 0x5000, 0x0, 0x0, 0x0)
	c:/go/src/internal/poll/fd_windows.go:731 +0x450
net.(*netFD).Write(0xc00013ef00, 0xc00089b000, 0x4c, 0x5000, 0x7e4f42, 0x1, 0xc0005efe38)
	c:/go/src/net/fd_windows.go:164 +0x56
net.(*conn).Write(0xc0000f6210, 0xc00089b000, 0x4c, 0x5000, 0x0, 0x0, 0x0)
	c:/go/src/net/net.go:196 +0x6f
io.copyBuffer(0xf140c8, 0xc0003cb820, 0xf140e8, 0xc0003e86e0, 0xc00089b000, 0x5000, 0x5000, 0x8d1100, 0xc000205200, 0xf140e8)
	c:/go/src/io/io.go:404 +0x202
io.CopyBuffer(0xf140c8, 0xc0003cb820, 0xf140e8, 0xc0003e86e0, 0xc00089b000, 0x5000, 0x5000, 0x1000000010000, 0xc0002ed9e0, 0x0)
	c:/go/src/io/io.go:375 +0x89
github.com/Dreamacro/clash/tunnel.relay.func1(0x9b21e0, 0xc0003cb820, 0x8da00e8, 0xc0003e86e0, 0xc0003244e0)
	C:/golang-projects/clash/tunnel/connection.go:122 +0x134
created by github.com/Dreamacro/clash/tunnel.relay
	C:/golang-projects/clash/tunnel/connection.go:120 +0xaa

**Comment by a936838** [comment]
> @a936838 有测试其他配置文件能否正常吗？
> 
> panic: runtime error: slice bounds out of range [2030:1120]
> 上面这个错误看起来像是内核的问题

国外媒体[🇭🇰 香港HKT-10G(8)]"
time="2020-02-20T17:10:19+08:00" level=info msg="[TCP] 127.0.0.1:52893 --> sb.scorecardresearch.com match DomainSuffix using 🛑 全球拦截[REJECT]"
time="2020-02-20T17:10:19+08:00" level=info msg="[TCP] 127.0.0.1:52894 --> sb.scorecardresearch.com match DomainSuffix using 🛑 全球拦截[REJECT]"
time="2020-02-20T17:10:29+08:00" level=info msg="[TCP] 127.0.0.1:52899 --> sb.scorecardresearch.com match DomainSuffix using 🛑 全球拦截[REJECT]"
time="2020-02-20T17:10:39+08:00" level=info msg="[TCP] 127.0.0.1:52904 --> sb.scorecardresearch.com match DomainSuffix using 🛑 全球拦截[REJECT]"
time="2020-02-20T17:10:49+08:00" level=info msg="[TCP] 127.0.0.1:52910 --> sb.scorecardresearch.com match DomainSuffix using 🛑 全球拦截[REJECT]"
time="2020-02-20T17:10:53+08:00" level=info msg="[TCP] 127.0.0.1:52913 --> clients4.google.com match DomainKeyword using 🔰 节点选择[🇭🇰 香港HKT-10G(8)]"
time="2020-02-20T17:10:59+08:00" level=info msg="[TCP] 127.0.0.1:52917 --> sb.scorecardresearch.com match DomainSuffix using 🛑 全球拦截[REJECT]"
time="2020-02-20T17:11:09+08:00" level=info msg="[TCP] 127.0.0.1:52921 --> sb.scorecardresearch.com match DomainSuffix using 🛑 全球拦截[REJECT]"
panic: runtime error: slice bounds out of range [2030:76]

goroutine 788 [running]:
internal/poll.(*FD).Write(0xc00013ef00, 0xc00089b000, 0x4c, 0x5000, 0x0, 0x0, 0x0)
c:/go/src/internal/poll/fd_windows.go:731 +0x450
net.(*netFD).Write(0xc00013ef00, 0xc00089b000, 0x4c, 0x5000, 0x7e4f42, 0x1, 0xc0005efe38)
c:/go/src/net/fd_windows.go:164 +0x56
net.(*conn).Write(0xc0000f6210, 0xc00089b000, 0x4c, 0x5000, 0x0, 0x0, 0x0)
c:/go/src/net/net.go:196 +0x6f
io.copyBuffer(0xf140c8, 0xc0003cb820, 0xf140e8, 0xc0003e86e0, 0xc00089b000, 0x5000, 0x5000, 0x8d1100, 0xc000205200, 0xf140e8)
c:/go/src/io/io.go:404 +0x202
io.CopyBuffer(0xf140c8, 0xc0003cb820, 0xf140e8, 0xc0003e86e0, 0xc00089b000, 0x5000, 0x5000, 0x1000000010000, 0xc0002ed9e0, 0x0)
c:/go/src/io/io.go:375 +0x89
github.com/Dreamacro/clash/tunnel.relay.func1(0x9b21e0, 0xc0003cb820, 0x8da00e8, 0xc0003e86e0, 0xc0003244e0)
C:/golang-projects/clash/tunnel/connection.go:122 +0x134
created by github.com/Dreamacro/clash/tunnel.relay
C:/golang-projects/clash/tunnel/connection.go:120 +0xaa

我是小白不太懂 请问该如何修

**Comment by Fndroid** [comment]
是不是和其他软件搭配使用？

**Comment by a936838** [comment]
翻墙软件吗？我一般就开一个，没有同时使用，我一般就打打绝地求生 然后网上看看YOUTUBE TWITCH
同时用的只有雷神加速器 YY STEAM 之类的
> 是不是和其他软件搭配使用？

**Comment by Fndroid** [comment]
是怎么连接的Clash，浏览器插件吗？

**Comment by a936838** [comment]
> 是怎么连接的Clash，浏览器插件吗？

用的就是您开发的这个clash for windows呀，安卓我用的clash for android，手机基本没问题 就是电脑的基本十几分钟就会连不上core

**Comment by Fndroid** [comment]
这个错误是socks端口才会有的，所以你应该不是直接开system proxy用，是不是有其他软件连这个socks5 port

**Comment by a936838** [comment]
> 这个错误是socks端口才会有的，所以你应该不是直接开system proxy用，是不是有其他软件连这个socks5 port

我用的Chrome，也没设置过代理 都是直接用的，我应该怎么查是什么占用了端口呢？

**Comment by giraffeAlpaca** [comment]
![image](https://user-images.githubusercontent.com/35832953/75152800-d91a6600-5744-11ea-9399-1f8d796d3e87.png)
The same problem as you.
I've use shadowsocks before and not used to system proxy. Switchyomega for chrome and proxifier for other applications.
Since I transfer to clash, this problem has occured. After this, I totally close switchyomega and proxifier and reboot my computer, carefully making sure there is no other proxy running or auto-start. However the problem still exists. I've check all ports and 9090 7890 7891 1080 are not occupied.

2020-02-24-202834.log
time="2020-02-24T20:28:34+08:00" level=info msg="HTTP proxy listening at: 127.0.0.1:7890"

**Comment by TargetMoon** [comment]
今天也出现了这种问题，应该是火绒的原因，退出火绒再重开就没问题了。

**Comment by a936838** [comment]
> ![image](https://user-images.githubusercontent.com/35832953/75152800-d91a6600-5744-11ea-9399-1f8d796d3e87.png)
> The same problem as you.
> I've use shadowsocks before and not used to system proxy. Switchyomega for chrome and proxifier for other applications.
> Since I transfer to clash, this problem has occured. After this, I totally close switchyomega and proxifier and reboot my computer, carefully making sure there is no other proxy running or auto-start. However the problem still exists. I've check all ports and 9090 7890 7891 1080 are not occupied.
> 
> 2020-02-24-202834.log
> time="2020-02-24T20:28:34+08:00" level=info msg="HTTP proxy listening at: 127.0.0.1:7890"

sad, seems like a lot of us are experiencing the same problem

**Comment by a936838** [comment]
> 今天也出现了这种问题，应该是与火绒有什么冲突，退出火绒再重开就没问题了。

我电脑里压根没有火绒这款软件啊，要不是刚刚百度一下 我都不知道这个是什么软件

**Comment by TargetMoon** [comment]
> > 今天也出现了这种问题，应该是与火绒有什么冲突，退出火绒再重开就没问题了。
> 
> 我电脑里压根没有火绒这款软件啊，要不是刚刚百度一下 我都不知道这个是什么软件

可以试试卸载clash后把旧的配置文件夹也删掉，重装，然后杀毒软件添加排除路径，我现在用着已经正常；也可能是win 10的系统应用占了代理端口，在任务管理器里把几个系统内置应用的进程关掉试试。

**Comment by KeSaite** [comment]
1.删除.clash或者.config以及该目录下所有文件(C:\Users\yourname\.config&.clash)
2.卸载软件
3.重装软件

**Comment by a936838** [comment]
> 1.删除.clash或者.config以及该目录下所有文件
> 
> * (C:\Users\yourname.config)
> * (C:\Users\yourname.clash)
> 
> 2.卸载软件
> 3.重装软件

试了不行

**Comment by ManassehZhou** [comment]
#445 感觉和这个问题一样
@a936838 
1. 运行一遍软件, 把C:\Users\<username>\.config\clash 里面的config.yaml的内容清空了
2. 重启软件

**Comment by Fndroid** [comment]
This issue is stale because it has been open 60 days with no activity. Remove stale label or comment or this will be closed in 7 days
