### ISSUE TITLE
[Bug]: 代理terminal中使用pnpm报错

### ISSUE THREAD

**Issue by YeeeeRQ** [Fndroid/clash_for_windows_pkg#4455]
### 请认真检查以下清单中的每一项

- [x] 已经搜索过，没有发现类似issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.23

### 操作系统

Windows x64

### 系统版本

Windows 10 LTSC

### 问题描述

pnpm node应用无法正常使用代理

### 复现步骤

CFW中点击Port选项里的终端按钮，使用终端。输入`pnpm dlx nuxi init nuxt-3-tutorial-1`
```shell
E:\Practice> pnpm dlx nuxi init nuxt-3-tutorial-1
node:internal/errors:490
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:399:5)
    at validateString (node:internal/validators:163:11)
    at Object.resolve (node:path:167:9)
    at ../node_modules/.pnpm/@pnpm+npm-conf@2.2.0/node_modules/@pnpm/npm-conf/lib/defaults.js (C:\Users\foo\AppData\Local\pnpm\global\5\.pnpm\registry.npmmirror.com+pnpm@8.5.1\node_modules\pnpm\dist\pnpm.cjs:15253:23)
    at __require (C:\Users\foo\AppData\Local\pnpm\global\5\.pnpm\registry.npmmirror.com+pnpm@8.5.1\node_modules\pnpm\dist\pnpm.cjs:12:50)
    at ../node_modules/.pnpm/@pnpm+npm-conf@2.2.0/node_modules/@pnpm/npm-conf/index.js (C:\Users\foo\AppData\Local\pnpm\global\5\.pnpm\registry.npmmirror.com+pnpm@8.5.1\node_modules\pnpm\dist\pnpm.cjs:15403:21)
    at __require (C:\Users\foo\AppData\Local\pnpm\global\5\.pnpm\registry.npmmirror.com+pnpm@8.5.1\node_modules\pnpm\dist\pnpm.cjs:12:50)
    at ../config/config/lib/index.js (C:\Users\foo\AppData\Local\pnpm\global\5\.pnpm\registry.npmmirror.com+pnpm@8.5.1\node_modules\pnpm\dist\pnpm.cjs:26204:39)
    at __require (C:\Users\foo\AppData\Local\pnpm\global\5\.pnpm\registry.npmmirror.com+pnpm@8.5.1\node_modules\pnpm\dist\pnpm.cjs:12:50)
    at ../cli/cli-utils/lib/getConfig.js (C:\Users\foo\AppData\Local\pnpm\global\5\.pnpm\registry.npmmirror.com+pnpm@8.5.1\node_modules\pnpm\dist\pnpm.cjs:46292:20) {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v18.15.0
```

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by Fndroid** [comment]
This issue is stale because it has been open 60 days with no activity. Remove stale label or comment or this will be closed in 7 days
