### ISSUE TITLE
[Bug]: $ ./cfw  libva error: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so init failed /bin/sh: 1: kill: No such process

### ISSUE THREAD

**Issue by shiiaii** [Fndroid/clash_for_windows_pkg#4464]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.23

### 操作系统

Linux

### 系统版本

ubuntu 20.04

### 问题描述

$ ./cfw 
libva error: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so init failed
/bin/sh: 1: kill: No such process

### 复现步骤

$ ./cfw 
libva error: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so init failed
/bin/sh: 1: kill: No such process

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by kzpsycheuu** [comment]
删除~/.config/clash   ~/.config/clash_win即可

**Comment by AYO-YO** [comment]
> 删除~/.config/clash ~/.config/clash_win即可

我遇到了同样的问题，且我删除这两个文件夹后仍然遇到此问题。

```txt
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Unsupported platform: linux-x64
    at Object.<anonymous> (/data/home/zcx/develop/tools/Clash/resources/app.asar/node_modules/@fndroid/network-interface/index.js:15:9)
    at Module._compile (node:internal/modules/cjs/loader:1141:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1196:10)
    at Module.load (node:internal/modules/cjs/loader:1011:32)
    at Module._load (node:internal/modules/cjs/loader:846:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/data/home/zcx/develop/tools/Clash/resources/app.asar/dist/electron/main.js:1:2582)
    at n (/data/home/zcx/develop/tools/Clash/resources/app.asar/dist/electron/main.js:1:124)
libva error: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so init failed
libva error: /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so init failed
```

**Comment by Fndroid** [comment]
This issue is stale because it has been open 60 days with no activity. Remove stale label or comment or this will be closed in 7 days
