### ISSUE TITLE
[Bug]: net.Addr is *net.IPAddr, not *net.IPNet

### ISSUE THREAD

**Issue by YuukyuuKikan** [Fndroid/clash_for_windows_pkg#4528]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.24

### 操作系统

Windows x64

### 系统版本

Windows10 22H2

### 问题描述

在尝试切换配置文件时报错，随后clash核心offline
panic: interface conversion: net.Addr is *net.IPAddr, not *net.IPNet

### 复现步骤

切换至拥有如下内容的配置文件，随后尝试更新任一订阅
```
mixed-port: 18888
allow-lan: true
bind-address: "*"
mode: rule
log-level: info
external-controller: 0.0.0.0:19090
secret: ""
routing-mark: 16666
experimental:
  ignore-resolve-fail: true
  sniff-tls-sni: true
  udp-fallback-match: true
profile:
  store-fake-ip: true
  store-selected: true
  tracing: true
ipv6: true
dns:
  enable: true
  listen: 0.0.0.0:1053
  ipv6: true
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
    - 1.1.1.1
  enhanced-mode: fake-ip
  nameserver:
    - 223.5.5.5
    - 119.29.29.29
    - dhcp://system
```

关键行：`- dhcp://system`

### 日志文件

<details><summary>logs</summary><p>

```
21:38:35 INF [API] listening addr=127.0.0.1:55442
21:38:35 INF [Inbound] Mixed(http+socks) listening addr=127.0.0.1:7890
21:38:35 WRN [TCP] dial failed error=lookup raw.githubusercontent.com: getaddrinfow: The requested name is valid, but no data of the requested type was found. proxy=DIRECT lAddr=127.0.0.1:55452 rAddr=raw.githubusercontent.com:443
21:38:35 WRN [TCP] dial failed error=lookup raw.githubusercontent.com: getaddrinfow: The requested name is valid, but no data of the requested type was found. proxy=DIRECT lAddr=127.0.0.1:55453 rAddr=raw.githubusercontent.com:443
21:38:35 INF [TCP] connected, doesn't match any rule lAddr=127.0.0.1:55454 rAddr=api.github.com:443 proxy=DIRECT
21:38:35 INF [Config] initial compatible provider name=🔰国外流量
21:38:35 INF [Config] initial compatible provider name=⚓️其他流量
21:38:35 INF [Config] initial compatible provider name=✈️Telegram
21:38:35 INF [Config] initial compatible provider name=🎬国外媒体
21:38:35 INF [Config] initial compatible provider name=🚀直接连接
21:38:35 INF [Config] initial compatible provider name=🎬Youtube
21:38:35 INF [Config] initial compatible provider name=🍎苹果服务
21:38:35 INF [Config] initial compatible provider name=🎬哔哩哔哩
21:38:35 INF [Config] initial compatible provider name=🎬Netflix
21:38:35 INF [DNS] server listening addr=[::]:53
21:38:50 INF [TCP] connected lAddr=127.0.0.1:55468 rAddr=az764295.vo.msecnd.net:443 mode=rule rule=DomainSuffix(msecnd.net) proxy=DIRECT
21:38:52 INF [TCP] connected lAddr=127.0.0.1:55470 rAddr=edge.microsoft.com:443 mode=rule rule=DomainSuffix(microsoft.com) proxy=DIRECT
21:38:52 INF [TCP] connected lAddr=127.0.0.1:55472 rAddr=www.bing.com:443 mode=rule rule=DomainSuffix(bing.com) proxy=🔰国外流量[上海电信转台湾HiNet2[M][倍率:1.2]]
21:38:55 INF [DNS] server listening addr=[::]:1053
21:39:09 WRN [Dialer] routing mark on socket is not supported on current platform
panic: interface conversion: net.Addr is *net.IPAddr, not *net.IPNet

goroutine 331 [running]:
github.com/Dreamacro/clash/component/iface.buildHolder.func1()
	github.com/Dreamacro/clash/component/iface/iface.go:59 +0x4e7
github.com/Dreamacro/clash/common/singledo.(*Single[...]).Do(0x5b5d4d5b33616e65, 0x105f210?)
	github.com/Dreamacro/clash/common/singledo/singledo.go:46 +0x1b2
github.com/Dreamacro/clash/component/iface.buildHolder()
	github.com/Dreamacro/clash/component/iface/iface.go:40 +0x2e
github.com/Dreamacro/clash/component/iface.ResolveInterface({0xc0005b4e27, 0x6})
	github.com/Dreamacro/clash/component/iface/iface.go:85 +0x25
github.com/Dreamacro/clash/dns.(*dhcpClient).invalidate(0xc00032c780)
	github.com/Dreamacro/clash/dns/dhcp.go:129 +0x96
github.com/Dreamacro/clash/dns.(*dhcpClient).resolve(0xc00032c780, {0x115b658, 0xc0007a2e10})
	github.com/Dreamacro/clash/dns/dhcp.go:60 +0x75
github.com/Dreamacro/clash/dns.(*dhcpClient).ExchangeContext(0x726f74736968227b?, {0x115b658, 0xc0007a2e10}, 0xe99481e8bdbee589?)
	github.com/Dreamacro/clash/dns/dhcp.go:45 +0x2c
github.com/Dreamacro/clash/dns.batchExchange.func1()
	github.com/Dreamacro/clash/dns/util.go:199 +0x35
github.com/Dreamacro/clash/common/picker.(*Picker[...]).Go.func1()
	github.com/Dreamacro/clash/common/picker/picker.go:67 +0x87
created by github.com/Dreamacro/clash/common/picker.(*Picker[...]).Go
	github.com/Dreamacro/clash/common/picker/picker.go:64 +0xaa
```

</p></details>

### 其他补充

暂时砍掉了这一行代码，不影响正常使用，可能某期取消支持了，仅提交供查阅。

**Comment by Fndroid** [comment]
This issue is stale because it has been open 60 days with no activity. Remove stale label or comment or this will be closed in 7 days
