### ISSUE TITLE
[Bug]: 0.20.29 Ubuntu 23.04 linux-x64 平台 安装更新后无法正常启动 clash

### ISSUE THREAD

**Issue by april211** [Fndroid/clash_for_windows_pkg#4669]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.29

### 操作系统

Linux

### 系统版本

Ubuntu 23.04, Linux 6.2.0-25-generic, 64-bit, X11, GNOME 44.2, AMD Ryzen™ 5 3500U with Radeon™ Vega Mobile Gfx × 8, AMD Radeon™ Vega 8 Graphics

### 问题描述

在 64位 Ubuntu 上安装 `0.20.29` 后无法启动程序，**使用相同的安装方法回滚到上一版本 `0.20.28` 后恢复正常**。

> After installing 0.20.29 on 64-bit Ubuntu, the program cannot be started. After rolling back to the previous version 0.20.28 using the same installation method, the software starts normally.

### 复现步骤

1. 在 clash for windows 中**点击更新按钮**（就是版本号），并转到浏览器下载页面**下载**成功
2. 使用如下命令更新（**之前也是如此更新，没有出现错误**）：
    ```
    cd ~/Downloads/
    mv Clash*.tar.gz clash.tar.gz
    sudo rm -rf /opt/clash/
    sudo tar -zxvf clash.tar.gz -C /opt/
    sudo mv /opt/Clash* /opt/clash
    rm -f clash.tar.gz
    ```
3. Terminal 中键入 `cfw`，尝试启动程序。（我已设置过环境变量）
4. Terminal 报错，显示平台不兼容。

*我后来又从 Github 手动下载了安装包，但是还是不行。*

### 日志文件

<details><summary>logs</summary><p>

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Unsupported platform: linux-x64
    at Object.<anonymous> (/opt/clash/resources/app.asar/node_modules/@fndroid/network-interface/index.js:15:9)
    at Module._compile (node:internal/modules/cjs/loader:1141:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1196:10)
    at Module.load (node:internal/modules/cjs/loader:1011:32)
    at Module._load (node:internal/modules/cjs/loader:846:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/opt/clash/resources/app.asar/dist/electron/main.js:1:2582)
    at n (/opt/clash/resources/app.asar/dist/electron/main.js:1:124)

```

</p></details>

### 其他补充

日志文件是 Terminal 的输出

PS **我认为我已经下载了正确的安装包**：

![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/53203590/0903567c-c2fc-48f5-9c56-15ab461de1a6)

*最后十分感谢作者对Linux平台的支持！*

**Comment by itstartstosnow** [comment]
The same error on Ubuntu 20.04.6 x64 system. 0.20.28 works

**Comment by AzunyanDaisuki** [comment]
Same error on Fedora 38 x64 system

**Comment by Fndroid** [comment]
下个版本修复

**Comment by yblpoi** [comment]
Same error on Archlinux  system
