### ISSUE TITLE
[Bug]: 0.20.29,linux x64版本运行错误，显示Error: Unsupported platform: linux-x64

### ISSUE THREAD

**Issue by YirunFantasy** [Fndroid/clash_for_windows_pkg#4670]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.29

### 操作系统

Linux

### 系统版本

debian 12

### 问题描述

现在换回0.20.28一切正常。29运行不了，下面就是终端在运行时候给的反馈信息
```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Unsupported platform: linux-x64
at Object.<anonymous> (/opt/clashwin/resources/app.asar/node_modules/@fndroid/network-interface/index.js:15:9)
at Module._compile (node:internal/modules/cjs/loader:1141:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1196:10)
at Module.load (node:internal/modules/cjs/loader:1011:32)
at Module._load (node:internal/modules/cjs/loader:846:12)
at f._load (node:electron/js2c/asar_bundle:2:13330)
at Module.require (node:internal/modules/cjs/loader:1035:19)
at require (node:internal/modules/cjs/helpers:102:18)
at Object.<anonymous> (/opt/clashwin/resources/app.asar/dist/electron/main.js:1:2582)
at n (/opt/clashwin/resources/app.asar/dist/electron/main.js:1:124)
[1766:0719/133708.040493:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
```

### 复现步骤

emm

### 日志文件

<details><summary>logs</summary><p>

```
进入Home Directory/logs文件夹，找到日志文件，将文件拖动至输入框或点击界面左下角小字，将打开文件内容粘贴替换这行
```

</p></details>

**Comment by april211** [comment]
#4669
