### ISSUE TITLE
[Bug]: A JavaScript Error occureed for Arm64 Windows (CFW v0.20.29)

### ISSUE THREAD

**Issue by PzkpfwV** [Fndroid/clash_for_windows_pkg#4673]
### 请认真检查以下清单中的每一项

- [X] 已经搜索过，没有发现类似issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 软件版本

0.20.29

### 操作系统

Windows x64

### 系统版本

Windows 11 Arm64 22H2 (OS Build 22621.1992)

### 问题描述

This error occured when I tried to  run "Clash For Windows.exe" for Windows Arm64.  ( In file "Clash.for.Windows-0.20.29-arm64-win.7z")

[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
Error: \\?\C:\Users\18750\AppData\Local\Temp\9ce937f0-1f56-477a-a3d3-76644ff3a398.tmp.node is not a valid Win32 application.
\\?\C:\Users\18750\AppData\Local\Temp\9ce937f0-1f56-477a-a3d3-76644ff3a398.tmp.node
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Module._extensions..node (node:internal/modules/cjs/loader:1226:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2049)
    at Module.load (node:internal/modules/cjs/loader:1011:32)
    at Module._load (node:internal/modules/cjs/loader:846:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1035:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at bindings (D:\18750\Downloads\CFW0.20.19\resources\app.asar\node_modules\bindings\bindings.js:112:48)
    at Object.<anonymous> (D:\18750\Downloads\CFW0.20.19\resources\app.asar\node_modules\@fndroid\network-interface\index.js:13:39)

[OK]

### 复现步骤

Just run the "Clash For Windows.exe" for Windows Arm64.

### 日志文件

There is no available log.

### 其他补充

![Snippet-20230719151946](https://github.com/Fndroid/clash_for_windows_pkg/assets/65943163/81ac1d96-9c2d-45a1-99f9-db6765822555)

https://github.com/Fndroid/clash_for_windows_pkg/assets/65943163/52610d7a-128a-45d3-96b5-17651e857233

**Comment by AlexNeOon** [comment]
I have the same error but in Ubuntu (Linux)
![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/138698529/01e92894-564d-4269-ade1-4f5ed95b96ca)

**Comment by AlexNeOon** [comment]
> I have the same error but in Ubuntu (Linux) ![image](https://user-images.githubusercontent.com/138698529/254504435-01e92894-564d-4269-ade1-4f5ed95b96ca.png)

The old version is working
![image](https://github.com/Fndroid/clash_for_windows_pkg/assets/138698529/01ccd1a4-f026-427b-b08d-29130b50ce6b)

**Comment by april211** [comment]
> > I have the same error but in Ubuntu (Linux) ![image](https://user-images.githubusercontent.com/138698529/254504435-01e92894-564d-4269-ade1-4f5ed95b96ca.png)
> 
> The old version is working ![image](https://user-images.githubusercontent.com/138698529/254506436-01ccd1a4-f026-427b-b08d-29130b50ce6b.png)

same here #4669

**Comment by Fndroid** [comment]
I will fix it for the next version

**Comment by silenter-su** [comment]
我的也出现了，mac 的PD 虚拟机，aarch64的windows11,也出现A JavaScript error occurred in the main process,作者您好，请问您是中国人吗？

> I will fix it for the next version

**Comment by silenter-su** [comment]
> I will fix it for the next version
请问下个版本什么时候可以出呀？

**Comment by blueokanna** [comment]
Even the x86 processor doesn't work

**Comment by april211** [comment]
新版放出来了xdm，我用的 Ubuntu 没问题～

**Comment by wangdongdong9264** [comment]
macbook m2 use PD  windows arm64 ，some this issue.

**Comment by wangdongdong9264** [comment]
> macbook m2 use PD windows arm64 ，some this issue. windows version: 25905.1000, mac version: 13.4.1 , App version: 0.20.29

use 0.20.30  install success

**Comment by Fndroid** [comment]
This issue is stale because it has been open 60 days with no activity. Remove stale label or comment or this will be closed in 7 days
