### ISSUE TITLE
win7 64位系统 看视频时每隔十分钟左右断链 clash报错

### ISSUE THREAD

**Issue by nomichan1** [Fndroid/clash_for_windows_pkg#499]
Windows 7 Ultimate SP1 build 7601

使用chrome浏览器看b站视频，或115浏览器看离线视频/下载时，在5-15分钟内有可能断网
报错后断链，主界面显示error，两段报错log如下：

panic: runtime error: slice bounds out of range [20480:7108]

goroutine 300801 [running]:
internal/poll.(*FD).Write(0xc000584c80, 0xc000795000, 0x1bc4, 0x5000, 0x0, 0x0, 0x0)
	c:/go/src/internal/poll/fd_windows.go:731 +0x450
net.(*netFD).Write(0xc000584c80, 0xc000795000, 0x1bc4, 0x5000, 0x7ed7c2, 0x1, 0xc00080fe38)
	c:/go/src/net/fd_windows.go:164 +0x56
net.(*conn).Write(0xc0003ac060, 0xc000795000, 0x1bc4, 0x5000, 0x0, 0x0, 0x0)
	c:/go/src/net/net.go:196 +0x6f
io.copyBuffer(0x4d919e8, 0xc000332620, 0x45f4378, 0xc000004dc0, 0xc000795000, 0x5000, 0x5000, 0x8d9d40, 0x0, 0x45f4378)
	c:/go/src/io/io.go:404 +0x202
io.CopyBuffer(0x4d919e8, 0xc000332620, 0x45f4378, 0xc000004dc0, 0xc000795000, 0x5000, 0x5000, 0x8, 0xc000020bd0, 0x438c3d)
	c:/go/src/io/io.go:375 +0x89
github.com/Dreamacro/clash/tunnel.relay.func1(0x9bc140, 0xc000332620, 0x45f4320, 0xc000004dc0, 0xc000024b40)
	C:/golang-projects/clash/tunnel/connection.go:122 +0x134
created by github.com/Dreamacro/clash/tunnel.relay
	C:/golang-projects/clash/tunnel/connection.go:120 +0xaa

--------------------------------------------------------------------------------------------------

panic: runtime error: slice bounds out of range [20480:8560]

goroutine 5014 [running]:
internal/poll.(*FD).Write(0xc0003f0280, 0xc000567000, 0x2170, 0x5000, 0x0, 0x0, 0x0)
	c:/go/src/internal/poll/fd_windows.go:731 +0x450
net.(*netFD).Write(0xc0003f0280, 0xc000567000, 0x2170, 0x5000, 0x7ed7c2, 0x1, 0xc000241e38)
	c:/go/src/net/fd_windows.go:164 +0x56
net.(*conn).Write(0xc0003e0080, 0xc000567000, 0x2170, 0x5000, 0x0, 0x0, 0x0)
	c:/go/src/net/net.go:196 +0x6f
io.copyBuffer(0x47400f8, 0xc0002b0900, 0x4740118, 0xc0002b0a20, 0xc000567000, 0x5000, 0x5000, 0x8d9d40, 0xc000241e00, 0x4740118)
	c:/go/src/io/io.go:404 +0x202
io.CopyBuffer(0x47400f8, 0xc0002b0900, 0x4740118, 0xc0002b0a20, 0xc000567000, 0x5000, 0x5000, 0xcc9520, 0xc0003a0630, 0x438c3d)
	c:/go/src/io/io.go:375 +0x89
github.com/Dreamacro/clash/tunnel.relay.func1(0x9bc140, 0xc0002b0900, 0x72900a0, 0xc0002b0a20, 0xc000066f60)
	C:/golang-projects/clash/tunnel/connection.go:122 +0x134
created by github.com/Dreamacro/clash/tunnel.relay

**Comment by Fndroid** [comment]
This issue is stale because it has been open 60 days with no activity. Remove stale label or comment or this will be closed in 7 days
